
// =============================================
// This Class is generated by BuildProject
// Author:	Bop
// Create date:	07/09/2016 20:08
// Description:	
// Revise History:	
// =============================================

using System;
using System.Data;
using System.Data.SqlClient;
using System.Data.Sql;
using System.Linq;
using System.Collections.Generic;
using BIT.Objects;
using BIT.Common;
using BIT.DataHelper;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace BIT.DataHelper
{ 
	public class COMMAND_DH : DataAccessBase
	{	
		public void InsertItem(COMMAND obj)
		{
			defaultDB.ExecuteNonQuery("sp_COMMAND_Insert"
				, obj.CommandCode, obj.UserCreate, obj.DateCreate);
		}

		public void UpdateItem(COMMAND obj)
		{
			defaultDB.ExecuteNonQuery("sp_COMMAND_Update"
				, obj.ID, obj.CommandCode, obj.UserCreate, obj.DateCreate);
		}

		public void DeleteItem(int ID)
		{
			defaultDB.ExecuteNonQuery("sp_COMMAND_Delete"
				, ID);
		}

		public COMMAND SelectItem(int ID)
		{
			return defaultDB.ExecuteSprocAccessor<COMMAND>("sp_COMMAND_SelectItem"
				, ID).FirstOrDefault();
		}

		public IEnumerable<COMMAND> SelectAllItems()
		{
			return defaultDB.ExecuteSprocAccessor<COMMAND>("sp_COMMAND_SelectAllItems");
		}

		public bool IsExistsItem(int ID)
		{
			IDataReader dr  = defaultDB.ExecuteReader("sp_COMMAND_SelectItem"
				, ID);
			
			bool bol = dr.Read();
			dr.Close();
			
			return bol;
		}
		
	}
}
