
// =============================================
// This Class is generated by BuildProject
// Author:	Bop
// Create date:	17/08/2016 11:31
// Description:	
// Revise History:	
// =============================================

using System;
using System.Data;
using System.Data.SqlClient;
using System.Data.Sql;
using System.Linq;
using System.Collections.Generic;
using BIT.Objects;
using BIT.Common;
using BIT.DataHelper;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace BIT.DataHelper
{ 
	public class SNUOC_DH : DataAccessBase
	{	
		public IEnumerable<SNUOC> SelectAllItems()
		{
			return defaultDB.ExecuteSprocAccessor<SNUOC>("sp_SNUOC_SelectAllItems");
		}
	}

    public class SPACKAGE_DH : DataAccessBase
    {
        public IEnumerable<SPACKAGE> SelectAllItems()
        {
            return defaultDB.ExecuteSprocAccessor<SPACKAGE>("sp_SPACKAGE_SelectAllItems");
        }

    }
}
