
// =============================================
// This Class is generated by BuildProject 
// Author:	Bop
// Create date:	17/08/2016 11:31
// Description:	
// Revise History:	
// =============================================

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using BIT.DataHelper;
using BIT.Objects;
using BIT.Common;

namespace BIT.Controller
{ 
	public class SNUOC_BC
	{
		private SNUOC_DH ctl = new SNUOC_DH();
				
		public List<SNUOC> SelectAllItems()
		{
			return ctl.SelectAllItems().ToList();
		}					
	}
}
