
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	24/08/2016 15:29
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class COMMISION_MONTHLY
    {

        public int ID { get; set; }

        public string CodeId { get; set; }

        public string Level { get; set; }

        public int? Month { get; set; }

        public int? Year { get; set; }

        public decimal? DOANH_SO_TRAI { get; set; }

        public decimal? DOANH_SO_PHAI { get; set; }

        public decimal? DOANH_SO_TICH_LUY_TRAI { get; set; }

        public decimal? DOANH_SO_TICH_LUY_PHAI { get; set; }

        public int? SO_THANH_VIEN_TRAI { get; set; }

        public int? SO_THANH_VIEN_PHAI { get; set; }

        public int? SO_THANH_VIEN_MOI_TRAI { get; set; }

        public int? SO_THANH_VIEN_MOI_PHAI { get; set; }

        public int? SO_THANH_VIEN_MOI_BAO_TRO_TRAI { get; set; }

        public int? SO_THANH_VIEN_MOI_BAO_TRO_PHAI { get; set; }

        public decimal? HOA_HONG_CO_BAN { get; set; }

        public decimal? HOA_HONG_CO_BAN_DUOC_TINH { get; set; }

        public string Username { get; set; }
        public string FullName { get; set; }
    }

    public class MonthlyCommision
    {
        public string DS_Value { get; set; }
        public string DS_Text { get; set; }
    }
}


