
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	17/08/2016 11:31
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class COMMISSION
    {

        public int ID { get; set; }

        public String CodeId { get; set; }

        public string CodeIDFrom { get; set; }

        public string UserFrom { get; set; }
        public decimal? Amount { get; set; }

        public DateTime? CreateDate { get; set; }

        public string type { get; set; }

        public int? SendID { get; set; }
    }
}


