
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	14/08/2016 23:47
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class MEMBERS
    {

        public int ID { get; set; }

        public string CodeId { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public string Password_PIN { get; set; }

        public string CodeId_Sponsor { get; set; }

        public string Fullname { get; set; }

        public string Phone { get; set; }

        public string Email { get; set; }

        public string Wallet { get; set; }

        public string Sys_Wallet { get; set; }

        public DateTime? CreateDate { get; set; }

        public string Level { get; set; }

        public int IsLock { get; set; }

        public string Country { get; set; }

        public string UpLine { get; set; }

        public int? Branch { get; set; }

        public int? Status { get; set; }
        public int? IsAdmin { get; set; }
        public int? IsVirtualWallet { get; set; }

    }
}


