
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	17/08/2016 11:31
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class PIN_TRANS
    {

        public int ID { get; set; }

        public string From { get; set; }

        public string To { get; set; }

        public int? Amout { get; set; }

        public string Transaction_Type { get; set; }
        
        public DateTime? Create_Date { get; set; }

    }
}


