
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	17/08/2016 11:31
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class RECHARGE
    {

        public int ID { get; set; }

        public String CodeId { get; set; }

        public String Username { get; set; }

        public DateTime CreateDate { get; set; }
        
        public string ReceiveWallet {get;set;}

        public string SendWallet {get;set;}

        public decimal? Amount {get;set;}

        public string Transaction {get;set;}

        public int Status {get;set;}

    }
}


