
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	17/08/2016 11:31
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class SNUOC
    {

        public int ID { get; set; }

        public string CODE { get; set; }

        public string NAME { get; set; }

    }

    public class SPACKAGE
    {
        public int ID { get; set; }

        public int PackageID { get; set; }

        public decimal PINAmount { get; set; }

        public string PackageName {get;set;}
    }
}


