
// =============================================
// This class is generated by BuildProject 
// Author:	Bop
// Create date:	17/08/2016 11:31
// Description:	
// Revise History:	
// =============================================
using System;

namespace BIT.Objects
{
    public class SWALLET
    {

        public int ID { get; set; }

        public string Wallet { get; set; }

        public string Member_ID { get; set; }

    }
}


